version: 2
  jobs:
  build:
    docker:
      - image: circleci/ruby:3.2.1
    
    steps:
      - checkout
      - run:
          name: Hello greeting
          command: echo Hello, CI/CD!
      - run:
          name: Print the time
          command: date
